package movie_booking;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {

    public static void main(String[] args) {

        
        String resourcePath = "src/main/resources/";

        LogicHandler movieBookings = new LogicHandler(new VirtConsole(), resourcePath);
        movieBookings.run();

    }
}
